# GitHub Sponsors
github: ["SilvaTechB"]

# Additional Sponsorship Platforms (if any, e.g., Open Collective or Patreon)
# Uncomment and replace URLs as needed
# patreon: [your-patreon-username]
# open_collective: [your-collective-name]
# ko_fi: [your-ko-fi-username]
# tidelift: [your-tidelift-project-url]
# custom: ["https://example.com/sponsor"]
